//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKASA
    {
        public int KASAID { get; set; }
        public byte DEFO { get; set; }
        public int SATISID { get; set; }
        public int KASATOPLAM { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
    
        public virtual TBLSATIS TBLSATIS { get; set; }
    }
}
